version: '3.8'

services:
  urlshortener:
    build: .
    container_name: urlshortener_container
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/urlshortener
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=urlshortener
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

